spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: client-ms
          uri: http://localhost:8081/
          predicates:
            - Path=/client/**
        - id: product-ms
          uri: http://localhost:8082/
          predicates:
            - Path=/product/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka