server:
  port: 8087
spring:
  application:
    name: balance-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always