server:
  port: 8081
spring:
  application:
    name: client-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/clientDB

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always