server:
  port: 8084
spring:
  application:
    name: credit-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/creditDB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always