server:
  port: 8085
spring:
  application:
    name: creditPay-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/creditPayDB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always