server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/creditTransactionDB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
      hostname: localhost