server:
  port: 8086
spring:
  application:
    name: deposit-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/depositDB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka