server:
  port: 8082
spring:
  application:
    name: product-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/productDB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always